version: 2.1
orbs:
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@1.3.0
  ansible-playbook: orbss/ansible-playbook@0.0.5
jobs:
  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t cloudformation/*.yml

  cloudformation:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
      - run:
          name: Check CircleCI IP Address
          command: |
            echo "Current CircleCI IP Address:"
            curl ifconfig.me
      - run:
          name: Deploy CloudFormation Stack
          command: |
            MY_CIDR_IP=$(curl -s http://checkip.amazonaws.com)/32
            set -x
            aws cloudformation deploy --template-file cloudformation/Network_Layer.yml --stack-name network
            aws cloudformation deploy --template-file cloudformation/Security_Layer.yml --stack-name security --parameter-overrides MyCidrIp=$MY_CIDR_IP
            aws cloudformation deploy --template-file cloudformation/Application_Layer.yml --stack-name application --capabilities CAPABILITY_NAMED_IAM

  ansible:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
      - run:
          name: Install Ansible
          command: |
            sudo apt-get update
            sudo apt-get install -y ansible
      - run:
          name: Install Nginx (for verification)
          command: |
            sudo apt-get update
            sudo apt-get install -y nginx
      - run:
          name: Update Security Group with Current IP
          command: |
            MY_CIDR_IP=$(curl -s http://checkip.amazonaws.com)/32
            echo "Updating Security Group with IP: $MY_CIDR_IP"

            # Check if the rule already exists
            EXISTING_RULE=$(aws ec2 describe-security-groups \
              --group-ids $SECURITY_GROUP_ID \
              --query "SecurityGroups[0].IpPermissions[?FromPort==\`22\` && ToPort==\`22\` && IpRanges[?CidrIp=='$MY_CIDR_IP']]" \
              --output text)

            if [ -z "$EXISTING_RULE" ]; then
              aws ec2 authorize-security-group-ingress \
                --group-id $SECURITY_GROUP_ID \
                --protocol tcp \
                --port 22 \
                --cidr $MY_CIDR_IP
            else
              echo "Rule already exists for IP: $MY_CIDR_IP"
            fi
      - run:
          name: Set up SSH Key
          command: |
            mkdir -p ~/.ssh
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
      - run:
          name: Check SSH Key Permissions
          command: |
            ls -la ~/.ssh/id_rsa
            cat ~/.ssh/id_rsa
      - run:
          name: Create Dynamic Inventory File
          command: |
            echo "[webserver]" > ansible/inventory.ini
            echo "webserver ansible_host=$TARGET_HOST ansible_user=$SSH_USER ansible_ssh_private_key_file=~/.ssh/id_rsa" >> ansible/inventory.ini
      - run:
          name: Display Inventory File
          command: cat ansible/inventory.ini
      - run:
          name: Test SSH Connection
          command: |
            ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -vvv $SSH_USER@$TARGET_HOST 'echo "SSH Connection Successful!"'
      - run:
          name: Run Ansible Playbook
          command: |
            ansible-playbook -i ansible/inventory.ini ansible/playbook.yml -vvv
      - run:
          name: Verify Nginx is installed and running
          command: |
            nginx -v
            ps aux | grep '[n]ginx'  # Check if nginx is running

  serverspec:
    docker:
      - image: cimg/ruby:2.7-node
    steps:
      - checkout
      - run:
          name: Wait for Nginx to be fully up and running
          command: sleep 10
      - run:
          name: Create .ssh directory if it doesn't exist
          command: mkdir -p ~/.ssh
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
      - run:
          name: Update Security Group with Current IP
          command: |
            MY_CIDR_IP=$(curl -s http://checkip.amazonaws.com)/32
            echo "Updating Security Group with IP: $MY_CIDR_IP"

            # Check if the rule already exists
            EXISTING_RULE=$(aws ec2 describe-security-groups \
              --group-ids $SECURITY_GROUP_ID \
              --query "SecurityGroups[0].IpPermissions[?FromPort==\`22\` && ToPort==\`22\` && IpRanges[?CidrIp=='$MY_CIDR_IP']]" \
              --output text)

            if [ -z "$EXISTING_RULE" ]; then
              aws ec2 authorize-security-group-ingress \
                --group-id $SECURITY_GROUP_ID \
                --protocol tcp \
                --port 22 \
                --cidr $MY_CIDR_IP
            else
              echo "Rule already exists for IP: $MY_CIDR_IP"
            fi
      - run:
          name: Copy SSH Config
          command: cp sshconfig/config ~/.ssh/
      - run:
          name: List directory to debug2
          command: ls -la
      - run:
          name: Check if Port 22 is Open on EC2 instance
          command: |
            echo "Public IP: $TARGET_HOST"
            nc -zv $TARGET_HOST 22 || exit 1
      - run:
          name: Check for Gemfile
          command: |
            if [ ! -f serverspec/Gemfile ]; then
              echo "Gemfile not found!"
              exit 1
            fi
      - run:
          name: Install Bundler
          command: gem install bundler
      - run:
          name: Configure Bundler Path
          command: |
            cd serverspec
            bundle config set --local path 'vendor/bundle'
      - run:
          name: bundle install
          command: |
            cd serverspec
            bundle install
      - run:
          name: Initialize Serverspec
          command: |
            cd serverspec
            bundle exec serverspec-init
      - run:
          name: execute
          command: |
            cd serverspec
            bundle exec rake spec

workflows:
  version: 2
  raisetech:
    jobs:
      - cfn-lint
      - cloudformation
      - ansible:
          requires:
            - cloudformation
      - serverspec:
          requires:
            - ansible