- hosts: webservers
  become: yes  # 管理者権限で実行するための設定
  tasks:
    - name: Print a message
      debug:
        msg: "Ansible playbook is running!"
    - name: Update APT package index (Ubuntu/Debian)
      apt:
        update_cache: yes
    - name: Install Nginx
      apt:
        name: nginx
        state: present
    - name: Check if Nginx is installed
      command: nginx -v
      ignore_errors: yes
    - name: Install Nginx from apt
      command: sudo apt-get install -y nginx
      become: yes
    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
    - name: Ensure Nginx is enabled on boot
      service:
        name: nginx
        enabled: yes
    - name: Wait for Nginx to start
      command: sleep 10
    - name: Check Nginx status
      command: systemctl status nginx