- hosts: webservers
  become: yes
  tasks:
    - name: Enable Nginx in Amazon Linux Extras
      command: amazon-linux-extras enable nginx1
      register: enable_nginx
      failed_when: enable_nginx.rc != 0
    - debug:
        var: enable_nginx

    - name: Install Nginx
      yum:
        name: nginx
        state: present
      register: nginx_install_result
      failed_when: nginx_install_result.failed
    - debug:
        var: nginx_install_result

    - name: Ensure Nginx is started and enabled
      service:
        name: nginx
        state: started
        enabled: yes
      register: nginx_service_status
    - debug:
        var: nginx_service_status

    - name: check nginx install
      shell: which nginx
      register: nginx_installed
      changed_when: false
      failed_when: nginx_installed.rc != 0
    - debug:
        var: nginx_installed