- hosts: webservers
  become: yes
  tasks:
    - name: Print a message
      debug:
        msg: "Ansible playbook is running!"

    - name: Update APT package index (Ubuntu/Debian)
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started

    - name: Ensure Nginx is enabled on boot
      service:
        name: nginx
        enabled: yes

    - name: Wait for Nginx to start
      command: sleep 10

    - name: Check if Nginx is installed
      command: which nginx
      register: nginx_path
      failed_when: nginx_path.stdout == ""

    - name: Check Nginx version
      command: nginx -v
      register: nginx_version
      failed_when: "'command not found' in nginx_version.stderr"

    - name: Check Nginx status
      command: systemctl status nginx
      register: nginx_status
      failed_when: "'not found' in nginx_status.stderr"