- hosts: webservers
  become: yes
  tasks:
    - name: Enable Nginx in Amazon Linux Extras
      command: amazon-linux-extras enable nginx1

    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Ensure Nginx is started and enabled
      service:
        name: nginx
        state: started
        enabled: yes

    - name: check nginx install
      shell: nginx -v
      register: nginx_installed
    - debug:
        var: nginx_installed