- hosts: webservers
  become: yes
  tasks:
    - name: Update yum cache
      yum:
        name: '*'
        state: latest

    - name: Enable Nginx in Amazon Linux Extras
      command: amazon-linux-extras enable nginx1
      register: enable_nginx
      failed_when: enable_nginx.rc != 0
    - debug:
        var: enable_nginx

    - name: Check Amazon Linux Extras for Nginx
      command: amazon-linux-extras list
      register: extras_list
    - debug:
        var: extras_list

    - name: Install Nginx
      yum:
        name: nginx
        state: present
      register: nginx_install_result
      failed_when: nginx_install_result.failed
    - debug:
        var: nginx_install_result

    - name: List installed packages (for Nginx)
      command: yum list installed | grep nginx
      register: nginx_installed_packages
      failed_when: nginx_installed_packages.rc != 0
    - debug:
        var: nginx_installed_packages

    - name: Ensure Nginx is started and enabled
      service:
        name: nginx
        state: started
        enabled: yes
      register: nginx_service_status
    - debug:
        var: nginx_service_status

    - name: Check Nginx binary location
      shell: "which nginx"
      register: nginx_path
      failed_when: nginx_path.rc != 0
    - debug:
        var: nginx_path