- hosts: webservers
  become: yes
  tasks:
    # 1. Amazon Linux ExtrasでNginxを有効化
    - name: Enable Nginx in Amazon Linux Extras
      command: amazon-linux-extras enable nginx1

    # 2. YumキャッシュをクリアしてからNginxをインストール
    - name: Clear Yum Cache
      command: yum clean all

    - name: Install Nginx
      yum:
        name: nginx
        state: present
      register: nginx_install_result
    - debug:
        var: nginx_install_result

    # 3. Nginxがインストールされたか確認
    - name: Check Nginx installation status
      command: "yum list installed | grep nginx"
      register: nginx_installed
      failed_when: nginx_installed.rc != 0
    - debug:
        var: nginx_installed

    # 4. Nginxのバイナリパスを確認
    - name: Find Nginx binary
      shell: "find / -name 'nginx' | grep bin"
      register: nginx_binary_path
      failed_when: nginx_binary_path.rc != 0
    - debug:
        var: nginx_binary_path

    # 5. パスにNginxが含まれていない場合、追加
    - name: Add Nginx to PATH
      shell: "export PATH=$PATH:/usr/sbin"
      when: "'/usr/sbin/nginx' in nginx_binary_path.stdout"

    # 6. Nginxを起動し、自動起動を有効化
    - name: Ensure Nginx is started and enabled
      service:
        name: nginx
        state: started
        enabled: yes

    # 7. Nginxが正しくインストールされ、動作しているかを確認
    - name: Check Nginx version
      shell: nginx -v
      register: nginx_version_check
    - debug:
        var: nginx_version_check