- name: Remove MariaDB
  become: true
  yum:
    name: mariadb-server
    state: absent

- name: Force remove mariadb-libs
  become: true
  yum:
    name: mariadb-libs
    state: absent
    remove: true
  ignore_errors: true

- name: Install MySQL repository
  become_user: root
  yum:
    name: 'https://repo.mysql.com//mysql80-community-release-el7-7.noarch.rpm'
    state: present
    disable_gpg_check: true
  register: mysql_installed

- name: Remove old GPG keys
  become_user: root
  rpm_key:
    state: absent
    key: https://repo.mysql.com/RPM-GPG-KEY-mysql
  ignore_errors: true

- name: Import new GPG key
  become_user: root
  rpm_key:
    state: present
    key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022

- name: install mysql-community-client
  become_user: root
  yum:
    name: mysql-community-client
    state: present
    disable_gpg_check: true
  when: mysql_installed.changed

- name: Install mysql-community-devel
  become_user: root
  yum:
    name: mysql-community-devel
    state: present
    disable_gpg_check: true
  when: mysql_installed.changed

- name: bin/setup
  shell: |
    bash -lc "bin/setup"
  args:
    chdir: "{{ sample_app_dir }}"
  when: mysql_installed.changed

- name: asset precompile
  shell: |
    bash -lc "rails assets:precompile"
  args:
    chdir: "{{ sample_app_dir }}"