- name: Clear yum cache
  become: true
  command: yum clean all

- name: Install MySQL repository (if not already installed)
  become: true
  yum:
    name: https://repo.mysql.com/mysql80-community-release-el7-11.noarch.rpm
    state: present
    disable_gpg_check: true

- name: Ensure mysql-community-client is installed
  become: true
  yum:
    name: mysql-community-client
    state: present
    disable_gpg_check: true

- name: Ensure mysql-community-devel is installed
  become: true
  yum:
    name: mysql-community-devel
    state: present
    disable_gpg_check: true

- name: Run setup script
  shell: |
    bash -lc "bin/setup"
  args:
    chdir: "{{ sample_app_dir }}"

- name: Precompile assets
  shell: |
    bash -lc "rails assets:precompile"
  args:
    chdir: "{{ sample_app_dir }}"