- name: Clear yum cache
  become: true
  command: yum clean all

- name: Rebuild yum cache
  become: true
  command: yum makecache

- name: Remove MariaDB
  become: true
  yum:
    name: mariadb-server
    state: absent
  ignore_errors: true
  register: mariadb_removed

- name: Force remove mariadb-libs with rpm
  become: true
  command: rpm -e --nodeps mariadb-libs
  when: mariadb_removed.failed
  ignore_errors: true

- name: Install MySQL repository (updated to el7-11)
  become_user: root
  yum:
    name: 'https://repo.mysql.com/mysql80-community-release-el7-11.noarch.rpm'
    state: present
    disable_gpg_check: true
  register: mysql_installed

- name: Remove old GPG keys
  become_user: root
  rpm_key:
    state: absent
    key: https://repo.mysql.com/RPM-GPG-KEY-mysql
  ignore_errors: true

- name: Import new GPG key
  become_user: root
  rpm_key:
    state: present
    key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022

- name: install mysql-community-client
  become_user: root
  yum:
    name: mysql-community-client
    state: present
    disable_gpg_check: true
    skip_broken: yes
  when: mysql_installed.changed

- name: Install mysql-community-devel
  become_user: root
  yum:
    name: mysql-community-devel
    state: present
    disable_gpg_check: true
    skip_broken: yes
  when: mysql_installed.changed

- name: bin/setup
  shell: |
    bash -lc "bin/setup"
  args:
    chdir: "{{ sample_app_dir }}"
  when: mysql_installed.changed

- name: asset precompile
  shell: |
    bash -lc "rails assets:precompile"
  args:
    chdir: "{{ sample_app_dir }}"