- name: Clear yum cache
  become: true
  command: yum clean all

- name: Remove existing MySQL GPG keys (if exist)
  become: true
  file:
    path: /etc/pki/rpm-gpg/RPM-GPG-KEY-mysql
    state: absent
  ignore_errors: true

- name: Remove existing MySQL 2022 GPG keys (if exist)
  become: true
  file:
    path: /etc/pki/rpm-gpg/RPM-GPG-KEY-mysql-2022
    state: absent
  ignore_errors: true

- name: Install MySQL repository
  become: true
  command: yum install -y https://repo.mysql.com/mysql80-community-release-el7-11.noarch.rpm --setopt=skip_broken=True --nogpgcheck

- name: Ensure mysql-community-client is installed
  become: true
  command: yum install -y mysql-community-client --setopt=skip_broken=True --nogpgcheck

- name: Ensure mysql-community-devel is installed
  become: true
  command: yum install -y mysql-community-devel --setopt=skip_broken=True --nogpgcheck

- name: Run setup script
  shell: |
    bash -lc "bin/setup"
  args:
    chdir: "{{ sample_app_dir }}"

- name: Precompile assets
  shell: |
    bash -lc "rails assets:precompile"
  args:
    chdir: "{{ sample_app_dir }}"