- name: Clear yum cache
  become: true
  command: yum clean all

- name: Remove old MySQL GPG keys (if exist)
  become: true
  file:
    path: /etc/pki/rpm-gpg/RPM-GPG-KEY-mysql
    state: absent
  ignore_errors: true

- name: Remove MySQL 2022 GPG keys (if exist)
  become: true
  file:
    path: /etc/pki/rpm-gpg/RPM-GPG-KEY-mysql-2022
    state: absent
  ignore_errors: true

- name: Rebuild yum cache
  become: true
  command: yum makecache

- name: Remove MariaDB
  become: true
  yum:
    name: mariadb-server
    state: absent
  ignore_errors: true
  register: mariadb_removed

- name: Force remove mariadb-libs with rpm
  become: true
  command: rpm -e --nodeps mariadb-libs
  when: mariadb_removed.failed
  ignore_errors: true

- name: Install MySQL repository (updated to el7-11)
  become: true
  yum:
    name: 'https://repo.mysql.com/mysql80-community-release-el7-11.noarch.rpm'
    state: present
    disable_gpg_check: true  # GPGチェックを無効に
  register: mysql_installed

- name: Install mysql-community-client
  become: true
  yum:
    name: mysql-community-client
    state: present
    disable_gpg_check: true  # GPGチェックを無効に
  when: mysql_installed.changed

- name: Install mysql-community-devel
  become: true
  yum:
    name: mysql-community-devel
    state: present
    disable_gpg_check: true  # GPGチェックを無効に
  when: mysql_installed.changed

- name: bin/setup
  shell: |
    bash -lc "bin/setup"
  args:
    chdir: "{{ sample_app_dir }}"
  when: mysql_installed.changed

- name: asset precompile
  shell: |
    bash -lc "rails assets:precompile"
  args:
    chdir: "{{ sample_app_dir }}"