# rpmのインストールを追加
- name: yum update all package
  become: true
  ansible.builtin.yum:
    name: "*"
    state: latest

- name: uninstall MariaDB
  become: true
  yum:
    name: mariadb*
    state: absent

# Import MySQL 2023 GPG key (GPGキーのインポート)
# Manually import MySQL GPG key using rpm command
- name: Manually import MySQL GPG key
  become: true
  shell: rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2023

# Install MySQL repository
- name: Install MySQL repository
  become: true
  yum:
    name: https://repo.mysql.com/mysql80-community-release-el7-11.noarch.rpm
    state: present
    disable_gpg_check: true

# Ensure mysql-community-client is installed
- name: Ensure mysql-community-client is installed
  become: true
  yum:
    name: mysql-community-client
    state: present

# Ensure mysql-community-devel is installed
- name: Ensure mysql-community-devel is installed
  become: true
  yum:
    name: mysql-community-devel
    state: present

# Run setup script
- name: Run setup script
  shell: |
    bash -lc "bin/setup"
  args:
    chdir: "{{ sample_app_dir }}"

# Precompile assets
- name: Precompile assets
  shell: |
    bash -lc "rails assets:precompile"
  args:
    chdir: "{{ sample_app_dir }}"