# rpmのインストールを追加
- name: install rpm
  yum:
    name: https://yum.puppetlabs.com/puppetlabs-release-pc1-el-11.noarch.rpm

- name: Clear yum cache
  become: true
  command: yum clean all

- name: Remove existing MySQL GPG keys
  become: true
  file:
    path: /etc/pki/rpm-gpg/RPM-GPG-KEY-mysql
    state: absent

- name: Remove existing MySQL 2022 GPG keys
  become: true
  file:
    path: /etc/pki/rpm-gpg/RPM-GPG-KEY-mysql-2022
    state: absent

- name: Install MySQL repository
  become: true
  yum:
    name: https://repo.mysql.com/mysql80-community-release-el7-11.noarch.rpm
    state: present

- name: Ensure mysql-community-client is installed
  become: true
  yum:
    name: mysql-community-client
    state: present

- name: Ensure mysql-community-devel is installed
  become: true
  yum:
    name: mysql-community-devel
    state: present

- name: Run setup script
  shell: |
    bash -lc "bin/setup"
  args:
    chdir: "{{ sample_app_dir }}"

- name: Precompile assets
  shell: |
    bash -lc "rails assets:precompile"
  args:
    chdir: "{{ sample_app_dir }}"