# rpmのインストールを追加
- name: yum update all package
  become: true
  ansible.builtin.yum:
    name: "*"
    state: latest

- name: Install pip
  become: true
  yum:
    name: python-pip
    state: present

- name: uninstall MariaDB
  become: true
  yum:
    name: mariadb*
    state: absent

- name: Install PyMySQL
  become: true
  pip:
    name: PyMySQL
    state: present

- name: Install pymysql using pip
  become: true
  pip:
    name: pymysql
    state: present



# Run setup script
- name: Run setup script
  shell: |
    bash -lc "bin/setup"
  args:
    chdir: "{{ sample_app_dir }}"

# Precompile assets
- name: Precompile assets
  shell: |
    bash -lc "rails assets:precompile"
  args:
    chdir: "{{ sample_app_dir }}"