---
- name: yum update all package
  become: true
  ansible.builtin.yum:
    name: "*"
    state: latest

- name: Install pip
  become: true
  yum:
    name: python-pip
    state: present

- name: uninstall MariaDB
  become: true
  yum:
    name: mariadb*
    state: absent

- name: Install PyMySQL
  become: true
  pip:
    name: PyMySQL
    state: present

- name: Install pymysql using pip
  become: true
  pip:
    name: pymysql
    state: present

- name: Install RPM-GPG-KEY-mysql
  become: true
  rpm_key:
    state: present
    key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022
  ignore_errors: true

- name: install myaql repository
  become: true
  yum:
    name: "https://repo.mysql.com//mysql84-community-release-el7-1.noarch.rpm"
    state: present

- name: install mysql packges
  become: true
  yum:
    name:
      - mysql-community-devel
      - mysql-community-server
      - mysql-community-client
    state: present


- name: Start MySQL service
  become: true
  systemd:
    name: mysqld
    state: started
  ignore_errors: true




- name: Start MySQL service
  become: true
  systemd:
    name: mysqld
    state: restarted